CREATE DATABASE surveipilkada;

CREATE TABLE tbl_user(
	`id` INT(11) NOT NULL PRIMARY KEY,
	`unique_id` VARCHAR(23) NOT NULL,
	`nama` VARCHAR(50) NOT NULL,
	`email` VARCHAR(100) NOT NULL,
	`encrypted_password` VARCHAR(80) NOT NULL,
	`salt` VARCHAR(10) NOT NULL)
CREATE TABLE tbl_pengumuman(
	`id` INT(10) NOT NULL PRIMARY KEY,
	  `judul` VARCHAR (500) NOT NULL,
	  `isi` VARCHAR(1000) NOT NULL) 
	  
	  ALTER TABLE `tbl_user`
  MODIFY `id` INT(10) NOT NULL AUTO_INCREMENT, AUTO_INCREMENT=10;
  ALTER TABLE `tbl_pengumuman`
  MODIFY `id` INT(11) NOT NULL AUTO_INCREMENT, AUTO_INCREMENT=2;COMMIT;